kind = "web"
previewPath = "/moniepoint-app/"
title = "Vexa"
version = "1.0.0"
id = "artifacts/moniepoint-app"
router = "path"

[[services]]
name = "web"
paths = [ "/moniepoint-app/" ]
localPort = 23935

[services.development]
run = "pnpm --filter @workspace/moniepoint-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/moniepoint-app", "run", "build" ]
serve = "static"
publicDir = "artifacts/moniepoint-app/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23935"
BASE_PATH = "/moniepoint-app/"
